version: "3.7"
services:
  db:
    image: postgres
    container_name: pg-docker
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
    volumes:
      - ./docker/volumes/postgres:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
